scalaVersion := "2.11.12"
name := "scala-spark-hello"
organization := "amit.learn"
version := "1.0"
libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % "2.4.4"
libraryDependencies += "org.apache.spark" % "spark-core_2.11" % "2.4.4"
